global:
  clusterInfo: {}
  # role: host
  # name: host 

costmodel:
  opencost:
    exporter:
      extraArgs: ["cost-model"]
      extraEnv:
        EXPORT_CSV_LABELS_LIST: kubesphere_io_workspace
        ETL_READ_ONLY: "true"
        CLUSTER_INFO_FILE_ENABLED: "true"
        CLUSTER_CACHE_FILE_ENABLED: "true"
      defaultClusterId: 'host'      
      image:
        registry: docker.io
        repository: frezes/opencost
        tag: dev
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      persistence:
        enabled: true
        annotations:
          "helm.sh/resource-policy": keep
        storageClass: ""
        accessMode: ReadWriteOnce
        size: 5Gi

    metrics:
      serviceMonitor:
        enabled: false

    customPricing:
      enabled: true
      costModel:
        description: Modified pricing configuration.
        CPU: 1.25
        spotCPU: 0.006655
        RAM: 0.50
        spotRAM: 0.000892
        GPU: 0.95
        storage: 0.25
        zoneNetworkEgress: 0.01
        regionNetworkEgress: 0.01
        internetNetworkEgress: 0.12

    prometheus:
      internal:
        enabled: false
        serviceName: prometheus-k8s
        namespaceName: kubesphere-monitoring-system
        port: 9090
      thanos:
        enabled: true
        internal:
          serviceName: query-frontend-whizard-operated
          namespaceName: kubesphere-monitoring-system
          port: 10902

exporter:
  opencost:
    exporter:
      extraArgs: ["agent"]
      extraEnv:
        KUBECOST_METRICS_PORT: 9003 

      image:
        registry: docker.io
        repository: frezes/opencost
        tag: dev
      securityContext:
        runAsUser: 0
        runAsNonRoot: false

    metrics:
      serviceMonitor:
        enabled: true

      config:
        enabled: false
        configmapName: custom-metrics
        disabledMetrics: []


    customPricing:
      enabled: true

    prometheus:
      internal:
        enabled: true
        serviceName: prometheus-k8s
        namespaceName: kubesphere-monitoring-system
        port: 9090

    ui:
      enabled: false