{{- if and .Values.opencost.customPricing.createConfigmap .Values.opencost.customPricing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencost.fullname" . }}-{{ .Values.opencost.customPricing.configmapName }}
  namespace: {{ include "opencost.namespace" . }}
data:
  {{ include "opencost.configFileName" . }}.json: |-
    {
{{- range $key, $val := .Values.opencost.customPricing.costModel }}
{{ $key | quote | indent 6}}: {{ $val | quote }},
{{- end}}
{{- if  eq .Values.opencost.customPricing.provider "custom" }}
      "clusterName" : {{ .Values.global.clusterInfo.name | default .Values.opencost.exporter.defaultClusterId | quote }},
{{- end }}
      "provider" : {{ .Values.opencost.customPricing.provider | quote }}
    }
{{- end }}
