{{- if .Values.opencost.exporter.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "opencost.fullname" . }}
  namespace: {{ include "opencost.namespace" . }}
  labels: {{- include "opencost.labels" . | nindent 4 }}
  {{- with .Values.opencost.exporter.persistence.annotations  }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.opencost.exporter.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.opencost.exporter.persistence.size | quote }}
  {{- if (lookup "v1" "PersistentVolumeClaim" (include "opencost.namespace" .) (include "opencost.fullname" .)) }}
  volumeName: {{ (lookup "v1" "PersistentVolumeClaim" (include "opencost.namespace" .) (include "opencost.fullname" .)).spec.volumeName }}
  {{- end }}
  {{- with .Values.opencost.exporter.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.opencost.exporter.persistence.selectorLabels }}
  selector:
    matchLabels:
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
